config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, :only => [:index, :show]

  get 'politicians/local' => 'politicians#local'
  get 'politicians/state' => 'politicians#state'
  get 'politicians/national' => 'politicians#national'
  resources :politicians

  authenticated do
    root :to => 'politicians#index', as: :authenticated
  end
  root :to => 'dashboard#home'
  get 'dashboard/about' => 'dashboard#about'



  resources :posts do
    resources :comments
  end

  resources :conversations do
    resources :messages
  end
  resources :events
  resources :spotlights
end

app/models/politician.rb
class Politician < ActiveRecord::Base
  has_many :voting_histories
  include HTTParty

  base_uri 'https://www.googleapis.com/civicinfo/us_v1/'
  default_params fields: "smallIcon,shortDescription"
  format :json

  def self.for politician
    get("", query: { query: politician})["elements"]
  end
end

app/controllers/politicians_controller.rb
class PoliticiansController < ApplicationController
  before_filter :authenticate_user!, except: [:home, :index]
  def index
    if user_signed_in?
      @user = current_user
      @posts = User.where(:state => current_user.state).joins(:posts).order("posts.created_at DESC").flat_map { |x| x.posts }
      @events = User.near(current_user).joins(:events).flat_map { |x| x.events }
      @politicians = collectPoliticians
      @spotlights = Spotlight.joins(:user).where("users.state = ?", current_user.state).order("spotlights.created_at DESC").limit(1).first
    else
      @posts = Post.near(params[:address])
      @politicians = collectPoliticians
      @events = Event.near(params[:address])
      @spotlights = Spotlight.near(params[:address]).first
    end
  end

  def show
  end

  def local
    @events = User.near(current_user).joins(:events).where("events.level = 'local'").flat_map { |x| x.events }
    @spotlights = User.near(current_user).joins(:spotlights).where("spotlights.level = 'local'").flat_map { |x| x.spotlights }
    @spotlights = Spotlight.joins(:user).near(current_user).where("spotlights.level = 'local'").order("spotlights.created_at DESC").limit(1).first
    @user = current_user
    @posts = User.near(current_user).joins(:posts).where("posts.level = 'local'").order("posts.created_at DESC").flat_map { |x| x.posts }
    @politicians = collectPoliticians
    @localOffices = []
    @offices.each do |office|
      if office.has_key? "levels"
      else
        @localOffices << office
      end
    end
  end

  def state
    @events = User.where(:state => current_user.state).joins(:events).where("events.level = 'state'").flat_map { |x| x.events }
    @user = current_user
    @spotlights = Spotlight.joins(:user).near(current_user).where("spotlights.level = 'state'").order("spotlights.created_at DESC").limit(1).first
    @posts = User.where(:state => current_user.state).joins(:posts).where("posts.level = 'state'").order("posts.created_at DESC").flat_map { |x| x.posts }
    @politicians = collectPoliticians
    @stateOffices = []
    @offices.each do |k, v|
      k.fetch("levels", []).each do |level|
        puts level
        if level == "administrativeArea1"
          @stateOffices << k
        end
      end
    end
  end

  def national
    @events = User.where(:state => current_user.state).joins(:events).where("events.level = 'national'").flat_map { |x| x.events }
    @user = current_user
    @posts = User.where(:state => current_user.state).joins(:posts).where("posts.level = 'national'").order("posts.created_at DESC").flat_map { |x| x.posts }
    @spotlights = Spotlight.joins(:user).near(current_user).where("spotlights.level = 'national'").order("spotlights.created_at DESC").limit(1).first
    @politicians = collectPoliticians
    @nationalOffices = []
    @offices.each do |k, v|
      k.fetch("levels", []).each do |level|
        puts level
        if level == "country"
          @nationalOffices << k
        end
      end
    end
  end

  def collectPoliticians
    if user_signed_in?
      addy = current_user.address
      address = URI.encode(addy)
    else
      address = URI.encode(params[:address])
    end
    response = HTTParty.get("https://www.googleapis.com/civicinfo/v2/representatives?address=#{address}&key=#{CI.key}")
    parsed_data = JSON.parse(response.body)
    @offices = parsed_data.fetch('offices', [])
    @officials = parsed_data['officials']
    @offices.each do |eli1|
      eli1["officials"] = eli1["officialIndices"].map { |idx|
        @officials[idx]
      }
      eli1.delete("officialIndices")
    end
    return [@offices, @officials]
  end
end

app/helpers/politicians_helper.rb
module PoliticiansHelper
end

app/views/politicians/_form.html.erb
<div class="modal fade" id="<%= "myPoliticianModal#{index}" %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <div class="modal-title" id="myModalLabel">
          <% office.fetch('officials', []).each do |official| %>
            <h4><strong><%= official['name'] %></strong></h4>
            <p class="individual-lines"><%= official['party'] %> Party</p>
          <% end %>
        </div>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-4">
            <% office.fetch('officials', []).each do |official| %>
              <% if official['photoUrl'].nil? %>
                <div class="imageContainer">
                  <%= image_tag('no-profile-img.gif') %>
                </div>
              <% else %>
                <div class="imageContainer">
                  <img src="<%= official['photoUrl']%>"/>
                </div>
              <% end %>
            <% end %>
          </div>
          <div class="col-md-8">
            <% if office['name'].present? %>
              <p><%= office["name"] %></p>
            <% end %>
            <% office.fetch('officials', []).each do |official| %>
              <% official.fetch('address', []).each do |el1, el2| %>
                <p><%= el1['line1'].titleize %></p>
                <% if el1['line2'].present? %>
                  <p><%= el1['line2'].titleize %></p>
                <% end %>
                <p><%= el1['city'].titleize %>, <%= el1['state'].upcase %> <%= el1['zip'].titleize %></p>
              <% end %>
              <p><%= official.fetch('phones', [])[0] %></p>
              <% official.fetch('urls', []).each do |url| %>
                <p><a href="<%=url%>">Official Website</a></p>
              <% end %>
              <% official.fetch('emails', []).each do |email| %>
                <p><%= email %></p>
              <% end %>
              <div class="row">
                <div class="col-sm-4"></div>
                <div class="col-sm-5">
                  <% official.fetch('channels', []).each do |channel| %>
                    <% if channel['type'].downcase == 'facebook' %>
                      <a href="https://www.facebook.com/<%= channel['id'] %>"><i class="fa fa-facebook-official fa-3x" aria-hidden="true"></i></a>
                    <% elsif channel['type'].downcase == 'twitter' %>
                      <a href="https://www.twitter.com/<%= channel['id'] %>"><i class="fa fa-twitter-square fa-3x" aria-hidden="true"></i></a>
                    <% elsif channel['type'].downcase == 'youtube' %>
                      <a href="https://www.youtube.com/<%= channel['id'] %>"><i class="fa fa-youtube fa-3x" aria-hidden="true"></i></a>
                    <% end %>
                  <% end %>
                </div>
                <div class="col-sm-3"></div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/politicians/index.html.erb
<% if user_signed_in? %>
<h4>Welcome to Assembly Point, <strong><%= @user.username %></strong>!</h4>
<% else %>
<h3> Welcome to  ASSEMBLY POINT.</h3>
<h5>Sign up today for the full experience!</h5>
<% end %>
<hr class="welcome-hr" />
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <div class="dash-grids">
        <div class='column-header'>
          <h4>Your Elected Officials</h4>
          <hr />
        </div>
        <% @offices.each.with_index do |office, index| %>
          <%= render :partial => 'politicians/form', locals: { office: office, index: index } %>
          <div class='politician-office'>
            <% office["officials"].each do |key, val| %>
              <p>
                <a href="<%= "#myPoliticianModal#{index}" %>" data-toggle="modal" data-target="<%= "#myPoliticianModal#{index}" %>", class: "nav-link">
                  <strong><%= key["name"] %></strong>
                </a>
              </p>
              <h5><%= office["name"] %></h5>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="dash-grids">
        <div class='column-header'>
          <h4>Posts Feed</h4>
          <hr />
        </div>
        <div class="post-feed">
          <% if @posts.empty? %>
            <p>You have no posts.</p>
          <% end %>
          <% @posts.each do |post| %>
              <h4><strong><a href="<%= post.body %>"><%= post.title %></a></strong></h4>
              <div class="posts-links">
                <p>posted by <%= link_to post.user.username, user_path(post.user.id), method: :get %> <%= time_ago_in_words(post.created_at) %> ago</p>
              </div>
              <div class="posts-links-two">
                <% if post.comments.count > 1 %>
                  <strong class="view_post_link"><i class="fa fa-comment-o" aria-hidden="true"></i>  <%= link_to "#{post.comments.count} comments", post_path(post.id), method: :get %></strong>
                <% elsif post.comments.count == 0 %>
                  <strong class="view_post_link"><i class="fa fa-comment-o" aria-hidden="true"></i>  <%= link_to "#{post.comments.count} comments", post_path(post.id), method: :get %></strong>
                <% else %>
                  <strong class="view_post_link"><i class="fa fa-comment-o" aria-hidden="true"></i>  <%= link_to "#{post.comments.count} comment", post_path(post.id), method: :get %></strong>
                <% end %>
              </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-sm-3">
      <div class="dash-grids">
        <div class='column-header'>
          <h4>Spotlight</h4>
          <hr />
        </div>
        <% if @spotlights.nil? %>
          <p>You have no spotlighted events.<p>
        <% else %>
          <div class="spotlight-title">
            <h4><%= @spotlights.title %></h4>
          </div>
          <hr class="spotlight-hr" />
          <p>What is the <%= @spotlights.title %>?</p>
          <p><%= @spotlights.description %></p>
          <p>Date: <%= @spotlights.date %></p>
          <strong><a href=" <%=@spotlights.url %>">Click here for more information!</a></strong>
        <% end %>

      </div>
      <hr />
      <div class="dash-grids">
        <div class='column-header'>
          <h4>Upcoming Events</h4>
          <hr />
        </div>
        <% if @events.empty? %>
          <p>You have no upcoming events</p>
        <% end %>
        <% @events.each do |event| %>
          <strong><p class="individual-lines"><%= link_to event.title, event_path(event.id), method: :get %></p></strong>
          <p><%= event.date %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/politicians/local.html.erb
<h4>Keep up with your <%= current_user.city %>, <%= current_user.state %> area politicians, <%= current_user.username %>!</h4>

<hr class="welcome-hr" />
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <div class="dash-grids">
        <div class="column-header">
          <h4>Your Elected Officials</h4>
          <hr />
        </div>
        <% @localOffices.each.with_index do |office, index| %>
          <%= render :partial => 'politicians/form', locals: { office: office, index: index } %>
          <div class='politician-office'>
            <% office["officials"].each do |key, val| %>
              <p>
                <a href="<%= "#myPoliticianModal#{index}" %>" data-toggle="modal" data-target="<%= "#myPoliticianModal#{index}" %>", class: "nav-link">
                  <strong><%= key["name"] %></strong>
                </a>
              </p>
              <h5><%= office["name"] %></h5>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="dash-grids">
        <div class="column-header">
          <h4>Posts Feed</h4>
          <hr />
        </div>
        <div class="post-feed">
          <% if @posts.empty? %>
            <p>You have no posts.</p>
          <% end %>
          <% @posts.each do |post| %>
              <h4><strong><a href="<%= post.body %>"><%= post.title %></a></strong></h4>
              <div class="posts-links">
                <p>posted by <%= link_to post.user.username, user_path(post.user.id), method: :get %> <%= time_ago_in_words(post.created_at) %> ago</p>
              </div>
              <div class="posts-links-two">
                <% if post.comments.count > 1 %>
                  <strong class="view_post_link"><i class="fa fa-comment-o" aria-hidden="true"></i> <%= link_to "#{post.comments.count} comments", post_path(post.id), method: :get %></strong>
                <% elsif post.comments.count == 0 %>
                  <strong class="view_post_link"><i class="fa fa-comment-o" aria-hidden="true"></i> <%= link_to "#{post.comments.count} comments", post_path(post.id), method: :get %></strong>
                <% else %>
                  <strong class="view_post_link"><i class="fa fa-comment-o" aria-hidden="true"></i> <%= link_to "#{post.comments.count} comment", post_path(post.id), method: :get %></strong>
                <% end %>
              </div>
          <% end %>
        </div>
      </div>
      <br />
      <% if user_signed_in? %>
        <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#myCreatePostsModal" id="admin-buttons">
          Create Post
        </button>

        <div class="modal fade" id="myCreatePostsModal" tabindex="-1" role="dialog" aria-labelledby="myCreatePostsModal">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-header-text">Assembly Point</h4>
              </div>
              <div class="modal-body">
                <%= render 'posts/new', review: Post.new(user_id: current_user.id) %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-sm-3">
      <div class="dash-grids">
        <div class="column-header">
          <h4>Spotlight</h4>
          <hr />
        </div>
        <% if @spotlights.nil? %>
          <p>You have no spotlighted events.<p>
        <% else %>
          <div class="spotlight-title">
            <h4><%= @spotlights.title %></h4>
          </div>
          <hr class="spotlight-hr" />
          <p>What is <%= @spotlights.title %>?</p>
          <p><%= @spotlights.description %></p>
          <p>Date: <%= @spotlights.date %></p>
          <strong><a href=" <%=@spotlights.url %>">Click here for more information!</a></strong>
        <% end %>
        <br /><br />
        <% if current_user.admin? %>
          <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#newSpotlightModal" id="admin-buttons">
            Create Spotlight
          </button>
        <% end %>
      </div>
      <hr />
      <div class="dash-grids">
        <div class="column-header">
          <h4>Upcoming Events</h4>
          <hr />
        </div>
        <% if @events.empty? %>
          <p>You have no upcoming events</p>
        <% end %>
        <% @events.each do |event| %>
          <strong><p class="individual-lines"><%= link_to event.title, event_path(event.id), method: :get %></p></strong>
          <p><%= event.date %></p>
        <% end %>
        <% if current_user.admin? %>
          <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#newEventModal" id="admin-buttons">
            Create Event
          </button>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="newEventModal" tabindex="-1" role="dialog" aria-labelledby="newEventModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modal-header-text">Assembly Point</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'events/new' %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="newSpotlightModal" tabindex="-1" role="dialog" aria-labelledby="newSpotlightModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modal-header-text">Assembly Point</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'spotlights/new' %>
      </div>
    </div>
  </div>
</div>

app/views/politicians/national.html.erb
<h4>Keep up with your national politicians, <%= @user.username %>!</h4>
<hr class="welcome-hr" />
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <div class="dash-grids">
        <div class="column-header">
          <h4>Your Elected Officials</h4>
          <hr />
        </div>
        <% @nationalOffices.each.with_index do |office, index| %>
          <%= render :partial => 'politicians/form', locals: { office: office, index: index } %>
          <div class='politician-office'>
            <% office["officials"].each do |key, val| %>
              <p>
                <a href="<%= "#myPoliticianModal#{index}" %>" data-toggle="modal" data-target="<%= "#myPoliticianModal#{index}" %>", class: "nav-link">
                  <strong><%= key["name"] %></strong>
                </a>
              </p>
              <h5><%= office["name"] %></h5>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="dash-grids">
        <div class="column-header">
          <h4>Posts Feed</h4>
          <hr />
        </div>
        <div class="post-feed">
          <% if @posts.empty? %>
            <p>You have no posts.</p>
          <% end %>
          <% @posts.each do |post| %>
              <h4><strong><a href="<%= post.body %>"><%= post.title %></a></strong></h4>
              <div class="posts-links">
                <p>posted by <%= link_to post.user.username, user_path(post.user.id), method: :get %> <%= time_ago_in_words(post.created_at) %> ago</p>
              </div>
              <div class="posts-links-two">
                <% if post.comments.count > 1 %>
                  <strong class="view_post_link"><i class="fa fa-comment-o" aria-hidden="true"></i> <%= link_to "#{post.comments.count} comments", post_path(post.id), method: :get %></strong>
                <% elsif post.comments.count == 0 %>
                  <strong class="view_post_link"><i class="fa fa-comment-o" aria-hidden="true"></i> <%= link_to "#{post.comments.count} comments", post_path(post.id), method: :get %></strong>
                <% else %>
                  <strong class="view_post_link"><i class="fa fa-comment-o" aria-hidden="true"></i> <%= link_to "#{post.comments.count} comment", post_path(post.id), method: :get %></strong>
                <% end %>
              </div>
          <% end %>
        </div>
      </div>
      <br />
      <% if user_signed_in? %>
        <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#myCreatePostsModal" id="admin-buttons">
          Create Post
        </button>

        <div class="modal fade" id="myCreatePostsModal" tabindex="-1" role="dialog" aria-labelledby="myCreatePostsModal">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">New Post</h4>
              </div>
              <div class="modal-body">
                <%= render 'posts/new', review: Post.new(user_id: current_user.id) %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-sm-3">
      <div class="dash-grids">
        <div class="column-header">
          <h4>Spotlight</h4>
          <hr />
        </div>
        <% if @spotlights.nil? %>
          <p>You have no spotlighted events.<p>
        <% else %>
          <div class="spotlight-title">
            <h4><%= @spotlights.title %></h4>
          </div>
          <hr class="spotlight-hr" />
          <p>What is <%= @spotlights.title %>?</p>
          <p><%= @spotlights.description %></p>
          <p>Date: <%= @spotlights.date %></p>
          <strong><a class="spotlight-url" href=" <%=@spotlights.url %>">Click here for more information!</a></strong>
        <% end %>
        <br /><br />
        <% if current_user.admin? %>
          <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#newSpotlightModal" id="admin-buttons">
            Create Spotlight
          </button>
        <% end %>
      </div>
      <hr />
      <div class="dash-grids">
        <div class="column-header">
          <h4>Upcoming Events</h4>
          <hr />
        </div>
        <% if @events.empty? %>
          <p>You have no upcoming events</p>
        <% end %>
        <% @events.each do |event| %>
          <strong><p class="individual-lines"><%= link_to event.title, event_path(event.id), method: :get %></p></strong>
          <p><%= event.date %></p>
        <% end %>
        <% if current_user.admin? %>
          <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#newEventModal" id="admin-buttons">
            Create Event
          </button>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="newEventModal" tabindex="-1" role="dialog" aria-labelledby="newEventModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Assembly Point</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'events/new' %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="newSpotlightModal" tabindex="-1" role="dialog" aria-labelledby="newSpotlightModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Assembly Point</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'spotlights/new' %>
      </div>
    </div>
  </div>
</div>

app/views/politicians/show.html.erb
<h3><%= @comment.body %></h3>
<h3><%= @comment.user.username %>

app/views/politicians/state.html.erb
<h4>Keep up with your <%= @user.state %> politicians, <%= @user.username %>!</h4>
<hr class="welcome-hr" />
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <div class="dash-grids">
        <div class="column-header">
          <h4>Your Elected Officials</h4>
          <hr />
        </div>
        <% @stateOffices.each.with_index do |office, index| %>
          <%= render :partial => 'politicians/form', locals: { office: office, index: index } %>
          <div class='politician-office'>
            <% office["officials"].each do |key, val| %>
              <p>
                <a href="<%= "#myPoliticianModal#{index}" %>" data-toggle="modal" data-target="<%= "#myPoliticianModal#{index}" %>", class: "nav-link">
                  <strong><%= key["name"] %></strong>
                </a>
              </p>
              <h5><%= office["name"] %></h5>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="dash-grids">
        <div class="column-header">
          <h4>Posts Feed</h4>
          <hr />
        </div>
        <div class="post-feed">
          <% if @posts.empty? %>
            <p>You have no posts.</p>
          <% end %>
          <% @posts.each do |post| %>
            <h4><strong><a href="<%= post.body %>"><%= post.title %></a></strong></h4>
            <div class="posts-links">
              <p>posted by <%= link_to post.user.username, user_path(post.user.id), method: :get %> <%= time_ago_in_words(post.created_at) %> ago</p>
            </div>
            <div class="posts-links-two">
              <% if post.comments.count > 1 %>
                <strong class="view_post_link"><i class="fa fa-comment-o" aria-hidden="true"></i> <%= link_to "#{post.comments.count} comments", post_path(post.id), method: :get %></strong>
              <% elsif post.comments.count == 0 %>
                <strong class="view_post_link"><i class="fa fa-comment-o" aria-hidden="true"></i> <%= link_to "#{post.comments.count} comments", post_path(post.id), method: :get %></strong>
              <% else %>
                <strong class="view_post_link"><i class="fa fa-comment-o" aria-hidden="true"></i> <%= link_to "#{post.comments.count} comment", post_path(post.id), method: :get %></strong>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <br />
      <% if user_signed_in? %>
        <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#myCreatePostsModal" id="admin-buttons">
          Create Post
        </button>

        <div class="modal fade" id="myCreatePostsModal" tabindex="-1" role="dialog" aria-labelledby="myCreatePostsModal">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="modal-header-text">Assembly Point</h4>
              </div>
              <div class="modal-body">
                <%= render 'posts/new', review: Post.new(user_id: current_user.id) %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-sm-3">
      <div class="dash-grids">
        <div class="column-header">
          <h4>Spotlight</h4>
          <hr />
        </div>
        <% if @spotlights.nil? %>
          <p>You have no spotlighted events.<p>
        <% else %>
          <div class="spotlight-title">
            <h4><%= @spotlights.title %></h4>
          </div>
          <hr class="spotlight-hr" />
          <p>What is <%= @spotlights.title %>?</p>
          <p><%= @spotlights.description %></p>
          <p>Date: <%= @spotlights.date %></p>
          <strong><a href=" <%=@spotlights.url %>">Click here for more information!</a></strong>
        <% end %>
        <br /><br />
        <% if current_user.admin? %>
          <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#newSpotlightModal" id="admin-buttons">
            Create Spotlight
          </button>
        <% end %>
      </div>
      <hr />
      <div class="dash-grids">
        <div class="column-header">
          <h4>Upcoming Events</h4>
          <hr />
        </div>
        <% if @events.empty? %>
          <p>You have no upcoming events</p>
        <% end %>
        <% @events.each do |event| %>
          <strong><p class="individual-lines"><%= link_to event.title, event_path(event.id), method: :get %></p></strong>
          <p><%= event.date %></p>
        <% end %>
        <% if current_user.admin? %>
          <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#newEventModal" id="admin-buttons">
            Create Event
          </button>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="newEventModal" tabindex="-1" role="dialog" aria-labelledby="newEventModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modal-header-text">Assembly Point</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'events/new' %>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="newSpotlightModal" tabindex="-1" role="dialog" aria-labelledby="newSpotlightModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="modal-header-text">Assembly Point</h4>
      </div>
      <div class="modal-body">
        <%= render partial: 'spotlights/new' %>
      </div>
    </div>
  </div>
</div>