config/routes.rb
Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, :only => [:index, :show]

  get 'politicians/local' => 'politicians#local'
  get 'politicians/state' => 'politicians#state'
  get 'politicians/national' => 'politicians#national'
  resources :politicians

  authenticated do
    root :to => 'politicians#index', as: :authenticated
  end
  root :to => 'dashboard#home'
  get 'dashboard/about' => 'dashboard#about'



  resources :posts do
    resources :comments
  end

  resources :conversations do
    resources :messages
  end
  resources :events
  resources :spotlights
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  def as_json(_)
    super(include: :user)
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
  belongs_to :sender, class_name: :User
  belongs_to :recipient, class_name: :User

  has_many :messages, dependent: :destroy

  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?)
    OR (conversations.sender_id = ? AND conversations.recipient_id =?)",
    sender_id, recipient_id, recipient_id, sender_id)
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  geocoded_by :address
  after_validation :geocode

  def address
    user.address
  end 
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

end

app/models/politician.rb
class Politician < ActiveRecord::Base
  has_many :voting_histories
  include HTTParty

  base_uri 'https://www.googleapis.com/civicinfo/us_v1/'
  default_params fields: "smallIcon,shortDescription"
  format :json

  def self.for politician
    get("", query: { query: politician})["elements"]
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode

  belongs_to :user
  has_many :comments
  has_many :upvotes

  def upvote_count
    upvotes.count
  end

  def vote
    upvotes.count + 1
  end

  def address
    user.address
  end
end

app/models/spotlight.rb
class Spotlight < ActiveRecord::Base
  belongs_to :user
  geocoded_by :address
  after_validation :geocode

  def address
    user.address
  end
end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :upvotes
  has_many :comments
  has_many :sender_conversations, foreign_key: :sender_id, class_name: :Conversation
  has_many :recipient_conversations, foreign_key: :recipient_id, class_name: :Conversation
  has_many :posts
  has_many :events
  has_many :spotlights

  def conversations
     sender_conversations | recipient_conversations
  end

  def address
    [street, city, state, zip].compact.join(', ')
  end
end

app/models/voting_history.rb
class VotingHistory < ActiveRecord::Base
  belongs_to :politician
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
  
  def us_states
    [
      ['AK', 'AK'],
      ['AL', 'AL'],
      ['AR', 'AR'],
      ['AZ', 'AZ'],
      ['CA', 'CA'],
      ['CO', 'CO'],
      ['CT', 'CT'],
      ['DC', 'DC'],
      ['DE', 'DE'],
      ['FL', 'FL'],
      ['GA', 'GA'],
      ['HI', 'HI'],
      ['IA', 'IA'],
      ['ID', 'ID'],
      ['IL', 'IL'],
      ['IN', 'IN'],
      ['KS', 'KS'],
      ['KY', 'KY'],
      ['LA', 'LA'],
      ['MA', 'MA'],
      ['MD', 'MD'],
      ['ME', 'ME'],
      ['MI', 'MI'],
      ['MN', 'MN'],
      ['MO', 'MO'],
      ['MS', 'MS'],
      ['MT', 'MT'],
      ['NC', 'NC'],
      ['ND', 'ND'],
      ['NE', 'NE'],
      ['NH', 'NH'],
      ['NJ', 'NJ'],
      ['NM', 'NM'],
      ['NV', 'NV'],
      ['NY', 'NY'],
      ['OH', 'OH'],
      ['OK', 'OK'],
      ['OR', 'OR'],
      ['PA', 'PA'],
      ['RI', 'RI'],
      ['SC', 'SC'],
      ['SD', 'SD'],
      ['TN', 'TN'],
      ['TX', 'TX'],
      ['UT', 'UT'],
      ['VA', 'VA'],
      ['VT', 'VT'],
      ['WA', 'WA'],
      ['WI', 'WI'],
      ['WV', 'WV'],
      ['WY', 'WY']
    ]
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/spotlights_helper.rb
module SpotlightsHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assembly Point</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Bitter' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
</head>
<body>
    <div class="container">
        <nav class='navbar navbar-default'>
          <div class="container-fluid">
            <div class="navbar-header">
              <a class='navbar-brand'>
                <div class="logo-font">
                  <i class="fa fa-compass fa-2x" id="compass-logo" aria-hidden="true"></i>
                    <span class="logo-text">
                      Assembly Point
                    </span>
                </div>
              </a>
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" id="nav-toggle-button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>

            <div class='collapse navbar-collapse'>
              <% if user_signed_in? %>
                <ul class="nav navbar-nav navbar-right">
                  <li> <%= link_to "Home", politicians_path, class: "nav-link" %> </li>
                  <li> <%= link_to "Local", politicians_local_path, method: :get, class: "nav-link" %> </li>
                  <li> <%= link_to "State", politicians_state_path, method: :get, class: "nav-link" %> </li>
                  <li> <%= link_to "National", politicians_national_path, method: :get, class: "nav-link" %> </li>
                  <li class="nav-dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                      <div class="nav-dropdown-padding">
                        <li><p><%= link_to "Profile", user_path(current_user), method: :get %></p></li>
                        <li><p><%= link_to "Inbox", conversations_path, method: :get %></p></li>
                        <li><p><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %></p></li>
                      </div>
                    </ul>
                  </li>
                </ul>
              <% else %>
                <ul class="nav navbar-nav navbar-right">
                  <li> <%= link_to "Home", root_path, class: "nav-link" %> </li>
                  <li><a href="#mySignInModal" data-toggle="modal" data-target="#mySignInModal", class="nav-link">Sign In</a></li>
                  <li><a href="#mySignUpModal" data-toggle="modal" data-target="#mySignUpModal", class="nav-link">Sign Up</a></li>
                </ul>
              <% end %>
            </div>
          </div>
        </nav>
        <div class="modal fade" id="mySignInModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="modal-header-text">
                  <h4 class="modal-title" id="myModalLabel">Assembly Point</h4>
                </div>
              </div>
              <div class="modal-body">
                <%= render partial: 'devise/sessions/new' %>
              </div>
            </div>
          </div>
        </div>
        <div class="modal fade" id="mySignUpModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <div class="modal-header-text">
                  <h4 class="modal-title" id="myModalLabel">Assembly Point</h4>
                </div>
              </div>
              <div class="modal-body">
                <%= render partial: 'devise/registrations/new' %>
              </div>
            </div>
          </div>
        </div>
    <% flash.each do |key, value| %>
             <div class="alert alert-<%= key %> alert-dismissable">
                 <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                 <%= value %>
             </div>
    <% end %>
      <div class="bulk">
        <div class="borderBox">
  <%= yield %>
        </div>
      </div>
    </div>


</body>
<div class="container">
  <div class="margin-footer">
    <nav class="navbar navbar-default">
      <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-3">
          <p class="footer-padding-left">Created by <a class ="footer-link" href="https://github.com/reckocp">Colin Recko</a></p>
        </div>
        <div class="col-sm-6"></div>
        <div class="col-sm-1">
          <p class="footer-padding"><%= link_to "About", dashboard_about_path, method: :get, class: "footer-link" %></p>
        </div>
        <div class="col-sm-1"></div>
      </div>
    </nav>
  </div>  
</div>
</html>